[package]
name = "base256utf8-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7.15"
const-str = "0.4.3"
match-lookup = "0.1.0"

[profile.release]
debug = true

[dev-dependencies]
criterion = "0.3.6"
rand = "0.8.5"

[[bench]]
name = "benchie"
harness = false